apiVersion: v1
kind: Secret
metadata:
  name: opentelemetry-collector
  namespace: opentelemetry-collector
stringData:
  APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
