apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql
  namespace: examples
data:
  POSTGRES_DB: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: examples
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: S3c_r3t!
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-headless
  namespace: examples
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: examples
spec:
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app: postgresql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: examples
spec:
  replicas: 1
  serviceName: postgresql-headless
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: ${IMAGE}
          envFrom:
            - configMapRef:
                name: postgresql
            - secretRef:
                name: postgresql
          volumeMounts:
            - name: postgresql
              mountPath: /var/lib/postgresql/data
          ports:
            - name: tcp-postgresql
              containerPort: 5432
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
          resources:
            limits:
              cpu: 750m
              ephemeral-storage: 2Gi
              memory: 1536Mi
            requests:
              cpu: 500m
              ephemeral-storage: 50Mi
              memory: 1024Mi
  volumeClaimTemplates:
    - metadata:
        name: postgresql
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "4Gi"
