config:
  cluster:
    enabled: true
    replicas: 3

  jetstream:
    enabled: true

  websocket:
    enabled: true
    ingress:
      enabled: true
      hosts:
        - nats.local

  merge:
    accounts:
      SYS:
        users:
          - { user: sys, password: sys }

      EXAMPLE:
        jetstream: enabled
        users:
          - { user: example, password: example }

    system_account: SYS

service:
  merge:
    spec:
      type: LoadBalancer

natsBox:
  enabled: false
