service:
  merge:
    spec:
      type: LoadBalancer

natsBox:
  enabled: false

config:
  cluster:
    enabled: true
    replicas: 3

  resolver:
    enabled: true
    merge:
      type: full
      interval: 2m
      timeout: 1.9s

  jetstream:
    enabled: true
    fileStore:
      pvc:
        size: 10Gi

  websocket:
    enabled: true
    ingress:
      enabled: true
      hosts:
        - nats.local
        # - nats.${DOMAIN}
      # tlsSecretName: letsencrypt-staging-godaddy-tls
    merge:
      jwt_cookie: nats.jwt

  merge:
    operator: __CHANGE_ME__
    system_account: __CHANGE_ME__
    resolver_preload:
      SYS_ACCOUNT_ID: __CHANGE_ME__
