config:
  cluster:
    enabled: true
    replicas: 3

  jetstream:
    enabled: true

  merge:
    accounts:
      SYS:
        users:
          - { user: sys, password: sys }

      EXAMPLE:
        jetstream: enabled
        users:
          - { user: example, password: example }

    system_account: SYS

service:
  merge:
    spec:
      type: LoadBalancer

natsBox:
  enabled: false
