config:
  cluster:
    enabled: true
    replicas: 3

  jetstream:
    enabled: true

  merge:
    accounts:
      A:
        users:
          - { user: a, password: a }
      B:
        users:
          - { user: b, password: b }
    system_account: A

service:
  merge:
    spec:
      type: LoadBalancer

natsBox:
  enabled: false
