role: Agent

customConfig:
  data_dir: /vector-data-dir

  api:
    enabled: true
    address: 127.0.0.1:8686
    playground: false

  sources:
    kubernetes_logs:
      type: kubernetes_logs

  sinks:
    stdout:
      type: console
      inputs:
        - kubernetes_logs
      encoding:
        codec: json
    azure:
      type: azure_monitor_logs
      inputs:
        - kubernetes_logs
      customer_id: ${CUSTOMER_ID}
      shared_key: ${SHARED_KEY}
      log_type: K3sLogs
