---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-production-cloudflare
  namespace: cert-manager
spec:
  secretName: letsencrypt-production-cloudflare-tls
  issuerRef:
    name: letsencrypt-production-cloudflare
    kind: ClusterIssuer
  commonName: "*.${DOMAIN}"
  dnsNames:
    - ${DOMAIN}
    - "*.${DOMAIN}"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ""
