apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smtp4dev
  namespace: examples
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp4dev
  namespace: examples
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp4dev
  template:
    metadata:
      labels:
        app: smtp4dev
    spec:
      containers:
        - name: smtp4dev
          image: rnwood/smtp4dev:v3
          volumeMounts:
            - mountPath: /smtp4dev
              name: smtp4dev
          ports:
            - containerPort: 80
            - containerPort: 25
      volumes:
        - name: smtp4dev
          persistentVolumeClaim:
            claimName: smtp4dev
---
apiVersion: v1
kind: Service
metadata:
  name: smtp4dev
  namespace: examples
spec:
  selector:
    app: smtp4dev
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: smtp
      port: 25
      targetPort: 25
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smtp4dev
  namespace: examples
spec:
  # tls:
  #   - hosts:
  #       - smtp4dev.${DOMAIN}
  #     secretName: letsencrypt-staging-godaddy-tls
  rules:
    # - host: smtp4dev.${DOMAIN}
    - host: smtp4dev.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: smtp4dev
                port:
                  number: 80
