apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-job
              image: alpine
              command: ["/bin/sh", "-c", "echo 'Hello from Kubernetes CronJob!'"]
          restartPolicy: OnFailure
