zitadel:
  masterkey: MasterkeyNeedsToHave32Characters

  configmapConfig:
    ExternalSecure: true
    ExternalDomain: zitadel.local
    TLS:
      Enabled: false
    FirstInstance:
      Org:
        Machine:
          Machine:
            Username: zitadel-admin-sa
            Name: Admin
          MachineKey:
            Type: 1
    Database:
      Postgres:
        Host: postgresql
        Port: 5432
        Database: zitadel
        MaxOpenConns: 20
        MaxIdleConns: 10
        MaxConnLifetime: 30m
        MaxConnIdleTime: 5m
        User:
          SSL:
            Mode: disable
        Admin:
          SSL:
            Mode: disable

  secretConfig:
    Database:
      Postgres:
        User:
          Username: zitadel
          Password: S3c_r3t!
        Admin:
          Username: postgres
          Password: S3c_r3t!

service:
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: h2c

ingress:
  enabled: true
  hosts:
    - host: zitadel.local
      paths:
        - path: /
          pathType: Prefix
