zitadel:
  masterkey: MasterkeyNeedsToHave32Characters

  configmapConfig:
    ExternalSecure: true
    ExternalDomain: zitadel.${DOMAIN}
    TLS:
      Enabled: false
    DefaultInstance:
      SMTPConfiguration:
        SMTP:
          Host: smtp4dev:25
          User: empty
          Password: empty
        TLS: false
        From: zitadel@zitadel.${DOMAIN}
        FromName: ZITADEL
        ReplyToAddress: no-reply@zitadel.${DOMAIN}
    FirstInstance:
      Org:
        Machine:
          Machine:
            Username: zitadel-admin-sa
            Name: Admin
          MachineKey:
            Type: 1
    Database:
      Postgres:
        Host: postgresql
        Port: 5432
        Database: zitadel
        MaxOpenConns: 20
        MaxIdleConns: 10
        MaxConnLifetime: 30m
        MaxConnIdleTime: 5m
        User:
          SSL:
            Mode: disable
        Admin:
          SSL:
            Mode: disable
    ServicePing:
      Enabled: false
    Log:
      Level: warn
      Formatter:
        Format: json

  secretConfig:
    Database:
      Postgres:
        User:
          Username: zitadel
          Password: S3c_r3t!
        Admin:
          Username: postgres
          Password: S3c_r3t!

image:
  tag: latest

service:
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: h2c

ingress:
  enabled: true
  tls:
    - hosts:
        - zitadel.${DOMAIN}
      secretName: letsencrypt-staging-cloudflare-tls
  hosts:
    - host: zitadel.${DOMAIN}
      paths:
        - path: /
          pathType: Prefix

login:
  ingress:
    enabled: true
