apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job
  namespace: examples
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: cron-job
              image: alpine
              command:
                - /bin/sh
                - -c
                - echo "Hello from Kubernetes CronJob!"
          restartPolicy: Never
