apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app
  namespace: examples
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging-godaddy
    # cert-manager.io/cluster-issuer: letsencrypt-production-godaddy
spec:
  tls:
    - hosts:
        - "*.${DOMAIN}"
      secretName: web-app-letsencrypt-staging-godaddy-tls
      # secretName: web-app-letsencrypt-production-godaddy-tls
  rules:
    - host: www.${DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-app
                port:
                  number: 80
