apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app
  namespace: examples
spec:
  tls:
    - hosts:
        - ${DOMAIN}
      secretName: letsencrypt-staging-tls
      # secretName: letsencrypt-production-tls
  rules:
    - host: ${DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-app
                port:
                  number: 80
