apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-server-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-server
  template:
    metadata:
      labels:
        app: nats-server
    spec:
      containers:
        - name: nats-server
          image: nats:latest
          command: ["nats-server", "--jetstream", "--store_dir", "/nats"]
          ports:
            - containerPort: 4222
          volumeMounts:
            - name: nats-server
              mountPath: /nats
      volumes:
        - name: nats-server
          persistentVolumeClaim:
            claimName: nats-server-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nats-server
spec:
  selector:
    app: nats-server
  ports:
    - protocol: TCP
      port: 4222
      targetPort: 4222
  type: LoadBalancer
