apiVersion: batch/v1
kind: CronJob
metadata:
  name: host-access
  namespace: examples
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: host-access
              image: curlimages/curl
              command:
                - /bin/sh
                - -c
                - curl -fsSi http://${HOST_IP}:8000/example
              env:
                - name: HOST_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
          restartPolicy: Never
