apiVersion: batch/v1
kind: CronJob
metadata:
  name: host-access
  namespace: examples
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: host-access
              image: curlimages/curl
              command:
                - /bin/sh
                - -c
                - curl --fail -X GET http://localhost:8080/host
          restartPolicy: Never
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
